# Generated by Django 2.0.8 on 2020-10-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=12, null=True)),
                ('role', models.CharField(max_length=10)),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('loginStatus', models.CharField(max_length=12)),
                ('authantication', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
